### ISSUE TITLE
Let stan_package_model() accept path to Stan file

### ISSUE THREAD

**Issue by mbojan** [wlandau/instantiate#7]
It would be convenient to be able to feed `stan_package_model()` with just the path to Stan file (instead of `name`, `package`, and `library`). The benefits are:

1. Package writer can store Stan files wherever (including nested folder tree under `inst` in package sources).
2. During package development in RStudio a shim of `system.file()` is used to look up files in package sources (because the package is not installed). As it is right now loading the package with `devtools::load_all()` will not find Stan models (source or compiled) because `base::system.file()` is being called by **instantiate**.

**Comment by wlandau** [comment]
I prefer the opinionated structure of `inst/stan` and `name`/`package` because it ensures consistency and prevents the kinds of errors that come with unnecessary freedom to customize. In 46f5c09107a8b182ffcc2964023dd95e42dc8fc6 I added a workaround to use the `pkgload` shim of `system.file()` if it exists, which seems to make `pkgload::load_all()` work. `load_all()` does not compile the models because compilation is driven by the `configure` script, but you can compile them as needed with `instantiate::stan_package_compile()`.

**Comment by wlandau** [comment]
That would be a better approach if feasible, both for models and for cmdstan itself, although I am not familiar enough with Stan internals at this point.
